/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSuccessRouteImport } from './routes/_authed/success'
import { Route as AuthedFormRouteImport } from './routes/_authed/form'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedDemoTanstackQueryRouteImport } from './routes/_authed/demo/tanstack-query'
import { Route as AuthedDemoStartServerFuncsRouteImport } from './routes/_authed/demo/start.server-funcs'
import { Route as AuthedDemoStartApiRequestRouteImport } from './routes/_authed/demo/start.api-request'
import { Route as AuthedDemoFormAddressRouteImport } from './routes/_authed/demo/form.address'
import { Route as AuthedDemoApiTqTodosRouteImport } from './routes/_authed/demo/api.tq-todos'
import { Route as AuthedDemoApiNamesRouteImport } from './routes/_authed/demo/api.names'
import { Route as AuthedDemoStartSsrIndexRouteImport } from './routes/_authed/demo/start.ssr.index'
import { Route as AuthedDemoStartSsrSpaModeRouteImport } from './routes/_authed/demo/start.ssr.spa-mode'
import { Route as AuthedDemoStartSsrFullSsrRouteImport } from './routes/_authed/demo/start.ssr.full-ssr'
import { Route as AuthedDemoStartSsrDataOnlyRouteImport } from './routes/_authed/demo/start.ssr.data-only'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSuccessRoute = AuthedSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedFormRoute = AuthedFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDemoTanstackQueryRoute = AuthedDemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDemoStartServerFuncsRoute =
  AuthedDemoStartServerFuncsRouteImport.update({
    id: '/demo/start/server-funcs',
    path: '/demo/start/server-funcs',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedDemoStartApiRequestRoute =
  AuthedDemoStartApiRequestRouteImport.update({
    id: '/demo/start/api-request',
    path: '/demo/start/api-request',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedDemoFormAddressRoute = AuthedDemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDemoApiTqTodosRoute = AuthedDemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDemoApiNamesRoute = AuthedDemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDemoStartSsrIndexRoute = AuthedDemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDemoStartSsrSpaModeRoute =
  AuthedDemoStartSsrSpaModeRouteImport.update({
    id: '/demo/start/ssr/spa-mode',
    path: '/demo/start/ssr/spa-mode',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedDemoStartSsrFullSsrRoute =
  AuthedDemoStartSsrFullSsrRouteImport.update({
    id: '/demo/start/ssr/full-ssr',
    path: '/demo/start/ssr/full-ssr',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedDemoStartSsrDataOnlyRoute =
  AuthedDemoStartSsrDataOnlyRouteImport.update({
    id: '/demo/start/ssr/data-only',
    path: '/demo/start/ssr/data-only',
    getParentRoute: () => AuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/form': typeof AuthedFormRoute
  '/success': typeof AuthedSuccessRoute
  '/demo/tanstack-query': typeof AuthedDemoTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof AuthedDemoApiNamesRoute
  '/demo/api/tq-todos': typeof AuthedDemoApiTqTodosRoute
  '/demo/form/address': typeof AuthedDemoFormAddressRoute
  '/demo/start/api-request': typeof AuthedDemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof AuthedDemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof AuthedDemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof AuthedDemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof AuthedDemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof AuthedDemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/form': typeof AuthedFormRoute
  '/success': typeof AuthedSuccessRoute
  '/': typeof AuthedIndexRoute
  '/demo/tanstack-query': typeof AuthedDemoTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof AuthedDemoApiNamesRoute
  '/demo/api/tq-todos': typeof AuthedDemoApiTqTodosRoute
  '/demo/form/address': typeof AuthedDemoFormAddressRoute
  '/demo/start/api-request': typeof AuthedDemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof AuthedDemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof AuthedDemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof AuthedDemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof AuthedDemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof AuthedDemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_authed/form': typeof AuthedFormRoute
  '/_authed/success': typeof AuthedSuccessRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/demo/tanstack-query': typeof AuthedDemoTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/demo/api/names': typeof AuthedDemoApiNamesRoute
  '/_authed/demo/api/tq-todos': typeof AuthedDemoApiTqTodosRoute
  '/_authed/demo/form/address': typeof AuthedDemoFormAddressRoute
  '/_authed/demo/start/api-request': typeof AuthedDemoStartApiRequestRoute
  '/_authed/demo/start/server-funcs': typeof AuthedDemoStartServerFuncsRoute
  '/_authed/demo/start/ssr/data-only': typeof AuthedDemoStartSsrDataOnlyRoute
  '/_authed/demo/start/ssr/full-ssr': typeof AuthedDemoStartSsrFullSsrRoute
  '/_authed/demo/start/ssr/spa-mode': typeof AuthedDemoStartSsrSpaModeRoute
  '/_authed/demo/start/ssr/': typeof AuthedDemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/form'
    | '/success'
    | '/demo/tanstack-query'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/logout'
    | '/form'
    | '/success'
    | '/'
    | '/demo/tanstack-query'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/_authed/form'
    | '/_authed/success'
    | '/_authed/'
    | '/_authed/demo/tanstack-query'
    | '/api/auth/$'
    | '/_authed/demo/api/names'
    | '/_authed/demo/api/tq-todos'
    | '/_authed/demo/form/address'
    | '/_authed/demo/start/api-request'
    | '/_authed/demo/start/server-funcs'
    | '/_authed/demo/start/ssr/data-only'
    | '/_authed/demo/start/ssr/full-ssr'
    | '/_authed/demo/start/ssr/spa-mode'
    | '/_authed/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/success': {
      id: '/_authed/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof AuthedSuccessRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/form': {
      id: '/_authed/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof AuthedFormRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/demo/tanstack-query': {
      id: '/_authed/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof AuthedDemoTanstackQueryRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/demo/start/server-funcs': {
      id: '/_authed/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof AuthedDemoStartServerFuncsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/demo/start/api-request': {
      id: '/_authed/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof AuthedDemoStartApiRequestRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/demo/form/address': {
      id: '/_authed/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof AuthedDemoFormAddressRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/demo/api/tq-todos': {
      id: '/_authed/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof AuthedDemoApiTqTodosRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/demo/api/names': {
      id: '/_authed/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof AuthedDemoApiNamesRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/demo/start/ssr/': {
      id: '/_authed/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof AuthedDemoStartSsrIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/demo/start/ssr/spa-mode': {
      id: '/_authed/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof AuthedDemoStartSsrSpaModeRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/demo/start/ssr/full-ssr': {
      id: '/_authed/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof AuthedDemoStartSsrFullSsrRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/demo/start/ssr/data-only': {
      id: '/_authed/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof AuthedDemoStartSsrDataOnlyRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedFormRoute: typeof AuthedFormRoute
  AuthedSuccessRoute: typeof AuthedSuccessRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedDemoTanstackQueryRoute: typeof AuthedDemoTanstackQueryRoute
  AuthedDemoApiNamesRoute: typeof AuthedDemoApiNamesRoute
  AuthedDemoApiTqTodosRoute: typeof AuthedDemoApiTqTodosRoute
  AuthedDemoFormAddressRoute: typeof AuthedDemoFormAddressRoute
  AuthedDemoStartApiRequestRoute: typeof AuthedDemoStartApiRequestRoute
  AuthedDemoStartServerFuncsRoute: typeof AuthedDemoStartServerFuncsRoute
  AuthedDemoStartSsrDataOnlyRoute: typeof AuthedDemoStartSsrDataOnlyRoute
  AuthedDemoStartSsrFullSsrRoute: typeof AuthedDemoStartSsrFullSsrRoute
  AuthedDemoStartSsrSpaModeRoute: typeof AuthedDemoStartSsrSpaModeRoute
  AuthedDemoStartSsrIndexRoute: typeof AuthedDemoStartSsrIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedFormRoute: AuthedFormRoute,
  AuthedSuccessRoute: AuthedSuccessRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedDemoTanstackQueryRoute: AuthedDemoTanstackQueryRoute,
  AuthedDemoApiNamesRoute: AuthedDemoApiNamesRoute,
  AuthedDemoApiTqTodosRoute: AuthedDemoApiTqTodosRoute,
  AuthedDemoFormAddressRoute: AuthedDemoFormAddressRoute,
  AuthedDemoStartApiRequestRoute: AuthedDemoStartApiRequestRoute,
  AuthedDemoStartServerFuncsRoute: AuthedDemoStartServerFuncsRoute,
  AuthedDemoStartSsrDataOnlyRoute: AuthedDemoStartSsrDataOnlyRoute,
  AuthedDemoStartSsrFullSsrRoute: AuthedDemoStartSsrFullSsrRoute,
  AuthedDemoStartSsrSpaModeRoute: AuthedDemoStartSsrSpaModeRoute,
  AuthedDemoStartSsrIndexRoute: AuthedDemoStartSsrIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
